version: '3.7'

services:
  web:
    build:
      context: .
      target: web
    image: role-backend/web
    ports:
      - ${DEV_PORT}:80
    volumes:
      - ./public:/var/www/public
    depends_on:
      - app-backend
    networks:
      - default

  app-backend:
    build:
      context: .
      target: app-backend
      args:
        APP_ENV: local
    image: role-backend/app
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=role-backend-database
      - DB_PORT=5432
    volumes:
      - /var/www/vendor
      - .:/var/www
    depends_on:
      - database
    networks:
      - default

  database:
    image: postgres:latest
    container_name: role-backend-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - default

networks:
  default:
